In [2]:
import pandas as pd

Loaded the Dataset

In [3]:
df=pd.read_csv(r"D:\Enterprise_ISTM_AI\data\raw\incident_event_log.csv")

Inspecting the values

In [4]:
df.head(5)

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

Size of the dataset

In [5]:
df.shape

(141712, 36)

Column names

In [6]:
df.columns

Index(['number', 'incident_state', 'active', 'reassignment_count',
       'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by',
       'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by',
       'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory',
       'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority',
       'assignment_group', 'assigned_to', 'knowledge',
       'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor',
       'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141712 entries, 0 to 141711
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   141712 non-null  object
 1   incident_state           141712 non-null  object
 2   active                   141712 non-null  bool
 3   reassignment_count       141712 non-null  int64
 4   reopen_count             141712 non-null  int64
 5   sys_mod_count            141712 non-null  int64
 6   made_sla                 141712 non-null  bool
 7   caller_id                141712 non-null  object
 8   opened_by                141712 non-null  object
 9   opened_at                141712 non-null  object
 10  sys_created_by           141712 non-null  object
 11  sys_created_at           141712 non-null  object
 12  sys_updated_by           141712 non-null  object
 13  sys_updated_at           141712 non-null  object
 14  contact_type             141712 non-null  object
 15  location                 141712 non-null  object
 16  category                 141712 non-null  object
 17  subcategory              141712 non-null  object
 18  u_symptom                141712 non-null  object
 19  cmdb_ci                  141712 non-null  object
 20  impact                   141712 non-null  object
 21  urgency                  141712 non-null  object
 22  priority                 141712 non-null  object
 23  assignment_group         141712 non-null  object
 24  assigned_to              141712 non-null  object
 25  knowledge                141712 non-null  bool
 26  u_priority_confirmation  141712 non-null  bool
 27  notify                   141712 non-null  object
 28  problem_id               141712 non-null  object
 29  rfc                      141712 non-null  object
 30  vendor                   141712 non-null  object
 31  caused_by                141712 non-null  object
 32  closed_code              141712 non-null  object
 33  resolved_by              141712 non-null  object
 34  resolved_at              141712 non-null  object
 35  closed_at                141712 non-null  object
dtypes: bool(4), int64(3), object(29)
memory usage: 35.1+ MB

Checking the data types

In [8]:
df.dtypes

number                     object
incident_state             object
active                       bool
reassignment_count          int64
reopen_count                int64
sys_mod_count               int64
made_sla                     bool
caller_id                  object
opened_by                  object
opened_at                  object
sys_created_by             object
sys_created_at             object
sys_updated_by             object
sys_updated_at             object
contact_type               object
location                   object
category                   object
subcategory                object
u_symptom                  object
cmdb_ci                    object
impact                     object
urgency                    object
priority                   object
assignment_group           object
assigned_to                object
knowledge                    bool
u_priority_confirmation      bool
notify                     object
problem_id                 object
rfc                        object
vendor                     object
caused_by                  object
closed_code                object
resolved_by                object
resolved_at                object
closed_at                  object
dtype: object

In [9]:
df.describe()

       reassignment_count   reopen_count  sys_mod_count
count       141712.000000  141712.000000  141712.000000
mean             1.104197       0.021918       5.080946
std              1.734673       0.207302       7.680652
min              0.000000       0.000000       0.000000
25%              0.000000       0.000000       1.000000
50%              1.000000       0.000000       3.000000
75%              1.000000       0.000000       6.000000
max             27.000000       8.000000     129.000000

Checking column Variables which are not numerical

In [10]:
cols=df.select_dtypes(include='object').columns
print(cols)

Index(['number', 'incident_state', 'caller_id', 'opened_by', 'opened_at',
       'sys_created_by', 'sys_created_at', 'sys_updated_by', 'sys_updated_at',
       'contact_type', 'location', 'category', 'subcategory', 'u_symptom',
       'cmdb_ci', 'impact', 'urgency', 'priority', 'assignment_group',
       'assigned_to', 'notify', 'problem_id', 'rfc', 'vendor', 'caused_by',
       'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='object')

Converting ? to NAN VALUES

In [11]:
df.replace('?',pd.NA,inplace=True)

In [12]:
df.isnull().sum()

number                          0
incident_state                  0
active                          0
reassignment_count              0
reopen_count                    0
sys_mod_count                   0
made_sla                        0
caller_id                      29
opened_by                    4835
opened_at                       0
sys_created_by              53076
sys_created_at              53076
sys_updated_by                  0
sys_updated_at                  0
contact_type                    0
location                       76
category                       78
subcategory                   111
u_symptom                   32964
cmdb_ci                    141267
impact                          0
urgency                         0
priority                        0
assignment_group            14213
assigned_to                 27496
knowledge                       0
u_priority_confirmation         0
notify                          0
problem_id                 139417
rfc                        140721
vendor                     141468
caused_by                  141689
closed_code                   714
resolved_by                   226
resolved_at                  3141
closed_at                       0
dtype: int64

Changing the date time values format to datetime

In [13]:
date_columns=['opened_at','sys_created_at','sys_updated_at','resolved_at']
for col in date_columns:
    df[col]=pd.to_datetime(df[col],errors='coerce')

C:\Users\bharg\AppData\Local\Temp\ipykernel_13664\2884995440.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col]=pd.to_datetime(df[col],errors='coerce')
C:\Users\bharg\AppData\Local\Temp\ipykernel_13664\2884995440.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col]=pd.to_datetime(df[col],errors='coerce')
C:\Users\bharg\AppData\Local\Temp\ipykernel_13664\2884995440.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col]=pd.to_datetime(df[col],errors='coerce')
C:\Users\bharg\AppData\Local\Temp\ipykernel_13664\2884995440.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col]=pd.to_datetime(df[col],errors='coerce')

In [14]:
df[date_columns].dtypes

opened_at         datetime64[ns]
sys_created_at    datetime64[ns]
sys_updated_at    datetime64[ns]
resolved_at       datetime64[ns]
dtype: object

In [15]:
print(df.duplicated().sum())

0

In [16]:
df.drop(columns=['cmdb_ci'],axis=1,inplace=True,errors='ignore')

In [17]:
#deleting closed_at column
df.drop(columns=['closed_at'],axis=1,inplace=True,errors='ignore')

In [26]:
#creating a temporary missing dataframe
missing=pd.DataFrame({'missing':df.isnull().sum(),
                      'missing_percentage':df.isnull().mean()*100})
missing=missing.sort_values(by='missing_percentage',ascending=False)
print(missing)

                         missing  missing_percentage
caused_by                 141689           99.983770
vendor                    141468           99.827820
rfc                       140721           99.300694
problem_id                139417           98.380518
sys_created_by             53076           37.453427
sys_created_at             53076           37.453427
u_symptom                  32964           23.261262
assigned_to                27496           19.402732
assignment_group           14213           10.029496
opened_by                   4835            3.411849
resolved_at                 3141            2.216467
closed_code                  714            0.503839
resolved_by                  226            0.159478
subcategory                  111            0.078328
category                      78            0.055041
location                      76            0.053630
caller_id                     29            0.020464
contact_type                   0            0.000000
u_priority_confirmation        0            0.000000
active                         0            0.000000
reassignment_count             0            0.000000
reopen_count                   0            0.000000
sys_mod_count                  0            0.000000
made_sla                       0            0.000000
notify                         0            0.000000
knowledge                      0            0.000000
opened_at                      0            0.000000
sys_updated_by                 0            0.000000
priority                       0            0.000000
urgency                        0            0.000000
impact                         0            0.000000
sys_updated_at                 0            0.000000
incident_state                 0            0.000000
number                         0            0.000000